apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nutanix-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nutanix-volume
  resources:
    requests:
      storage: 4Gi