# This file should be populated manually for each installation by obtaining 
# the block device and node name using the below command (Expect this to fail for the first time):
# kubectl get bd -A                                                                                                                                                                      ─╯
# NAMESPACE   NAME                                           NODENAME    SIZE           CLAIMSTATE   STATUS   AGE
# openebs     blockdevice-9e896ca287cb024292e959467c58f3f9   eksa-sa02   240057409536   Claimed      Active   49m
# openebs     blockdevice-f74ab1a7c662d258435fdb8e0395f91c   eksa-sa04   240057409536   Claimed      Active   49m
# openebs     blockdevice-f97121796c7e94f578751b0e4798de2f   eksa-sa03   240057409536   Claimed      Active   49m
apiVersion: cstor.openebs.io/v1
kind: CStorPoolCluster
metadata:
 name: cstor-disk-pool
 namespace: openebs
spec:
 pools:
   - nodeSelector:
       kubernetes.io/hostname: "10.2.32.20"
     dataRaidGroups:
       - blockDevices:
           - blockDeviceName: "blockdevice-1a33a8c1c0dba5b15b4db49a74fdc0e3"
     poolConfig:
       dataRaidGroupType: "stripe"
   - nodeSelector:
       kubernetes.io/hostname: "10.2.32.20"
     dataRaidGroups:
       - blockDevices:
           - blockDeviceName: "blockdevice-1a40758fa9aaece3263f973ab103c279"
     poolConfig:
       dataRaidGroupType: "stripe"
   - nodeSelector:
       kubernetes.io/hostname: "10.2.32.20"
     dataRaidGroups:
       - blockDevices:
           - blockDeviceName: "blockdevice-7a89d1d51cdc7ce0e34f2d91d2c09090"
     poolConfig:
       dataRaidGroupType: "stripe"