apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openebs-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-csi-cstor-sparse
  resources:
    requests:
      storage: 4Gi