---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cronjob-exporter-service-account
  namespace: default
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cronjob-exporter-clusterrole
  namespace: default
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cronjob-exporter-clusterrole-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: cronjob-exporter-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: cronjob-exporter-clusterrole
  apiGroup: rbac.authorization.k8s.io
