apiVersion: batch/v1
kind: Job
metadata:
  name: neuvector-testjob
  namespace: neuvector
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: job
          image: opensuse/leap
          command: ["curl", "-ks", "--location", "https://neuvector-service-webui.neuvector.svc.cluster.local:8443"]
      restartPolicy: Never
