apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nutanix-snapshot-restored-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nutanix-volume
  resources:
    requests:
      storage: 4Gi
  dataSource:
    name: nutanix-volume-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io